### ISSUE TITLE
サンプルコード(C版)で注文を発注すると、"銘柄コードが入力されていません (WPLE09001)" エラーになる

### ISSUE THREAD

**Issue by hiro935575** [sonicboom719/SBIClient#1]
サンプルの  C ソースの中で、以下のように注文を発注しようとすると"銘柄コードが入力されていません (WPLE09001)" エラーになります。

	order = SBICreateOrder(OD_MARGIN_SELL, OD_TOKYO, 3333, 100);
	SBISetOrderNariyuki(order, OD_NOCOND);
	SBISetOrderMargin(order, OD_IPPAN);
	SBISetOrderAzukari(order, OA_TOKUTEI);

	if ((rc = SBIStockOrder(order, &orderNumber)) < 0) {
		printf("StockOrder error = %d\n", rc);
		if (rc == SBI_UNKNOWN_ERROR)
			puts(SBIGetLastOrderErrorDescr());
		SBIReleaseOrder(order);
		return -1;
	}

**Comment by sonicboom719** [comment]
すみません、最新バージョンでの動作確認は行なっていないのでSBI証券のサイト仕様が変更された可能性があります。当方で直ぐに修正するのは難しいです。もし少々の仕様変更であればご自身でソース修正していただいて直る可能性があります。直った際は修正を共有いただけると非常に助かります。

**Comment by hiro935575** [comment]
結構仕様って変わるものなのですね... 私の方でも時間が出来た時に確認してみます!

**Comment by sonicboom719** [comment]
こちらで確認してみましたが、「銘柄コードが・・・」のエラーは出ないですね。普通に注文が成功します。信用売りではなくて現物買いで注文しても同じエラーが出ますか？

**Comment by hiro935575** [comment]
こちらですが、エラーが発生する時は送信パラメータの i_stock_sec が i_stock_sec_tmp に変更されていました。
しばらくすると、また i_stock_sec に戻りました。よって今のコードで動作すると思います。
アップデートしておらず申し訳ありませんでした。
